### ISSUE TITLE
"Could not read" error while installing the modpack

### ISSUE THREAD

**Issue by BlockLegend001** [AbdulMuqsit/Starpack-Aleph#124] opened 2021-12-30 17:03 UTC
**Describe the bug**
When I try to download the package it says "Could not read"

**Modpack Version**
 - [1.16.5] StarPack Titan (Starpack-Titan-0.1.8.zip)
 
**To Reproduce**
1) Go to 'Curseforge'

2) Click on 'install' to install the modpack

3) Error on the beginning of the installation :
Could not read
C:\Users\rosar\AppData\Local\Temp\CF\N9FyCNdhXECmc3RqhrZmkA1.zip as a zip file

**Expected behavior**
I expect for the modpack to be installed

**Screenshots**
![Cattura](https://user-images.githubusercontent.com/62543902/147772759-9321d29a-0d3c-43aa-ac62-40030e37b8c3.PNG)

**Logs**
I dont have it

**Comment by starmun-0010** [comment] 2021-12-30 20:25
Duplicate of #123

**Comment by starmun-0010** [comment] 2021-12-30 20:26
Can you please let me know if you are able to install the 0.1.8a version?

**Comment by BlockLegend001** [comment] 2021-12-31 09:31
it seems work with 0.1.8a version

**Comment by starmun-0010** [comment] 2021-12-31 10:37
Fixed in 0.1.8a

**Closed as completed by starmun-0010** 2021-12-31 10:37 UTC
Labels: bug, duplicate
